services:
  - type: web
    name: able-connect-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn able.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: able-connect-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: able-connect-backend.onrender.com
    healthCheckPath: /

databases:
  - name: able-connect-db
    plan: free
    databaseName: able_connect
    user: able_connect_user
